# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

# conda activate tobamo-snakemake
# snakemake -n already starts the download
# snakemake --use-conda -c40 -k -p


import os
import pandas as pd
from snakemake.utils import validate

os.system("workflow/scripts/download_sra.sh")


configfile: "config/config.yaml"


samples = pd.read_table(config["samples"])


wildcard_constraints:
    accession="ERR\d+|SRR\d+|DRR\d+",


ruleorder: spades_isolate_se > megahit_se
ruleorder: spades_isolate_pe > megahit_pe


##### Target rules #####


rule all:
    input:
        expand(
            "results/{accession}/09_{accession}_megan6_results.csv",
            accession=samples["samples"],
        ),
    output:
        "results/megan6_results_combined.csv",
    shell:
        """
        python workflow/scripts/combine_results.py {input} {output}
        """


##### Modules #####
DEBUG = True

if DEBUG:

    include: "rules/trim_debug.smk"

else:

    include: "rules/trim.smk"


include: "rules/assembly.smk"
include: "rules/filtering.smk"
include: "rules/diamond.smk"
include: "rules/megan6.smk"
